#!/bin/bash

# Steps:
# - read in a rotation from sequence file
# - identity rotation amount
# - remove cyclic movements using MOD(100)
# - increase counter by number of cyclic movements detected
# - detect movements across the '0' point creating a click
# - apply rotation and detect zero encounter (increase counter)
# - repeat until no new rotation entries
# - report counter as passcode

INPUT_FILE_PATH="./input"

dial=(50)
counter=(0)

while IFS= read -r rotation; do
    # log dial rotation
    printf "Dial=(%d),  Rotation=(%s)" $dial $rotation

    amount=${rotation[@]:1}

    # add cycles to counter
    (( counter+=((amount - (amount % 100)) / 100) ))

    # remove cycles
    (( amount %= 100 ))

    # ignore zero movements
    if [[ $amount -eq 0 ]]; then
        continue
    fi
    
    # track last dial position to detect clicks created from moving across the zero point
    dial_last=($dial)

    case $rotation in
        "R"*) (( dial += amount ));;
        "L"*) (( dial -= amount ));;
    esac
    
    if [[ $dial -gt 99 ]]; then
        (( dial-=100 ))
        (( dial_last != 0 && dial != 0 )) && (( counter++ ))
    elif [[ $dial -lt 0 ]]; then 
        (( dial+=100 ))
        (( dial_last != 0 && dial != 0 )) && (( counter++ ))
    fi

    [[ $dial == 0 ]] && (( counter++ ))

    # log dial position
    echo " Dial: " $dial

done < $INPUT_FILE_PATH

printf "\nPasscode= %d\n" $counter